struct MoviesRepository {
    static let movies = [Movie(title: "Star Trek Beyond",
                               subtitle: MoviesHelper.startrekBeyondDescription,
                               image: "startrek"),
                         Movie(title: "Starwars: The force awakens",
                               subtitle: MoviesHelper.starwarsDescription,
                               image: "starwars"),
                         Movie(title: "Avatar",
                               subtitle: MoviesHelper.avatarDescription,
                               image: "avatar"),
                         Movie(title: "Blade Runner",
                               subtitle: MoviesHelper.bladeRunnerDescription,
                               image: "bladerunner"),
                         Movie(title: "The Terminator",
                               subtitle: MoviesHelper.terminatorDescription,
                               image: "terminator"),
                         Movie(title: "Predator",
                               subtitle: MoviesHelper.predatorDescription,
                               image: "predator"),
                         Movie(title: "Dune",
                               subtitle: MoviesHelper.duneDescription,
                               image: "dune"),
                         Movie(title: "First Constact",
                               subtitle: MoviesHelper.firstContactDescription,
                               image: "firstcontact"),
                         Movie(title: "Dune",
                               subtitle: MoviesHelper.duneDescription,
                               image: "dune"),
                         Movie(title: "First Constact",
                               subtitle: MoviesHelper.firstContactDescription,
                               image: "firstcontact")]
}
